version: '3.8'
services:
  configsvr:
    image: mongo:6.0
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - ./data/configdb:/data/db
    networks:
      - mongo-cluster

  shard1:
    image: mongo:6.0
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - ./data/shard1:/data/db
    networks:
      - mongo-cluster

  mongos:
    image: mongo:6.0
    command: ["mongos", "--configdb", "configReplSet/configsvr:27019", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
